/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePublishThirdUrl = "publish_third_url"

// Knowledge knowledge tabke
type PublishThirdUrl struct {
	ID           int64  `gorm:"column:id;primaryKey;comment:id" json:"id"`                                        // id
	Introduction string `gorm:"column:introduction;not null;comment:链接介绍" json:"introduction"`                    // knowledge's name
	Url          string `gorm:"column:url;comment:url" json:"url"`                                                // app id // space id
	CreatedAt    int64  `gorm:"column:created_at;not null;comment:Create Time in Milliseconds" json:"created_at"` // Create Time in Milliseconds
	UpdatedAt    int64  `gorm:"column:updated_at;not null;comment:Update Time in Milliseconds" json:"updated_at"` // Update Time in Milliseconds // Delete Time
	Status       int32  `gorm:"column:status;not null;default:1;comment:0 删除, 1 正常" json:"status"`
	UrlType      int32  `gorm:"column:urlType;not null;default:1;comment:1 小红书" json:"urlType"`
	CreatorID    string `gorm:"column:creator_id;not null;comment:creator id" json:"creator_id"`
	LikeCount    int64  `gorm:"column:likeCount;not null;comment:点赞量" json:"likeCount"`
	CollectCount int64  `gorm:"column:collectCount;not null;comment:收藏量" json:"collectCount"`
	ChatCount    int64  `gorm:"column:chatCount;not null;comment:评论量" json:"chatCount"`
}

// TableName Knowledge's table name
func (*PublishThirdUrl) TableName() string {
	return TableNamePublishThirdUrl
}
