// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePublishThirdUrl = "publish_third_url"

// Knowledge knowledge tabke
type PublishThirdUrl struct {
	ID           int64  `gorm:"column:id;primaryKey;comment:id" json:"id"`                                        // id
	Introduction string `gorm:"column:introduction;not null;comment:链接介绍" json:"introduction"`                    // knowledge's name
	Url          string `gorm:"column:url;comment:url" json:"url"`                                                // app id // space id
	CreatedAt    int64  `gorm:"column:created_at;not null;comment:Create Time in Milliseconds" json:"created_at"` // Create Time in Milliseconds
	UpdatedAt    int64  `gorm:"column:updated_at;not null;comment:Update Time in Milliseconds" json:"updated_at"` // Update Time in Milliseconds // Delete Time
	Status       int32  `gorm:"column:status;not null;default:1;comment:0 删除, 1 正常" json:"status"`
	UrlType      int32  `gorm:"column:urlType;not null;default:1;comment:1 小红书" json:"urlType"`
	CreatorID    int64  `gorm:"column:creator_id;not null;comment:creator id" json:"creator_id"`
}

// TableName Knowledge's table name
func (*PublishThirdUrl) TableName() string {
	return TableNamePublishThirdUrl
}
