/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by hertz generator.

package coze

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/coze-dev/coze-studio/backend/api/model/publishThird"
	publishThird_commion "github.com/coze-dev/coze-studio/backend/api/model/publishThird/commion"
	application "github.com/coze-dev/coze-studio/backend/application/publishThird"
)

func UpdateTweetUrls(ctx context.Context, c *app.RequestContext) {
	var err error
	var req publishThird.GetThirdUrlRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		invalidParamRequestResponse(c, err.Error())
		return
	}

	resp := &publishThird.PublishThirdResponse[string]{
		Code:    0,
		Message: "ok",
	}
	switch req.GetThirdUrlType() {
	case publishThird_commion.LoginType_XSH:
		//小红书发布逻辑
		if req.LikeCount == nil {
			invalidParamRequestResponse(c, "LikeCount is nil")
		}
		if req.CollectCount == nil {
			invalidParamRequestResponse(c, "CollectCount is nil")
		}
		if req.ChatCount == nil {
			invalidParamRequestResponse(c, "ChatCount is nil")
		}
		if req.Id == nil {
			invalidParamRequestResponse(c, "id is nil")
		}

		resp, err = application.PublishThirdApplicationSVC.UpdateTweetUrl(ctx, &req)
		if err != nil {
			internalServerErrorResponse(ctx, c, err)
			return
		}
	}
	c.JSON(consts.StatusOK, resp)
}

func SaveTweetUrls(ctx context.Context, c *app.RequestContext) {
	var err error
	var req publishThird.GetThirdUrlRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		invalidParamRequestResponse(c, err.Error())
		return
	}

	resp := &publishThird.PublishThirdResponse[string]{
		Code:    0,
		Message: "ok",
	}
	switch req.GetThirdUrlType() {
	case publishThird_commion.LoginType_XSH:
		//小红书发布逻辑
		if req.Url == nil {
			invalidParamRequestResponse(c, "url is nil")
		}
		if req.Introduction == nil {
			invalidParamRequestResponse(c, "introduction is nil")
		}

		resp, err = application.PublishThirdApplicationSVC.SaveTweetUrl(ctx, &req)
		if err != nil {
			internalServerErrorResponse(ctx, c, err)
			return
		}
	}
	c.JSON(consts.StatusOK, resp)
}

func GetTweetUrls(ctx context.Context, c *app.RequestContext) {
	var err error
	var req publishThird.GetThirdUrlRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		invalidParamRequestResponse(c, err.Error())
		return
	}

	resp := &publishThird.PublishThirdResponse[[]*publishThird.PublishThirdUrl]{
		Code:    0,
		Message: "ok",
	}
	switch req.GetThirdUrlType() {
	case publishThird_commion.LoginType_XSH:
		//小红书发布逻辑
		resp, err = application.PublishThirdApplicationSVC.GetTweetUrlList(ctx, &req)
		if err != nil {
			internalServerErrorResponse(ctx, c, err)
			return
		}
	}
	c.JSON(consts.StatusOK, resp)
}

// 第三方登录
func LoginToXHS(ctx context.Context, c *app.RequestContext) {
	var err error
	var req publishThird.GetThirdLoginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		invalidParamRequestResponse(c, err.Error())
		return
	}

	resp := &publishThird.PublishThirdResponse[string]{
		Code:    0,
		Message: "ok",
	}
	switch req.GetThirdLoginType() {
	case publishThird_commion.LoginType_XSH:
		//小红书发布逻辑
		resp, err = application.PublishThirdApplicationSVC.XhsLogin(ctx, &req)
		if err != nil {
			internalServerErrorResponse(ctx, c, err)
			return
		}
	}
	c.JSON(consts.StatusOK, resp)
}

// 获取登录二维码
func GetXhsLoginQr(ctx context.Context, c *app.RequestContext) {
	var err error
	var req publishThird.GetThirdLoginRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		invalidParamRequestResponse(c, err.Error())
		return
	}

	resp := &publishThird.PublishThirdResponse[string]{
		Code:    0,
		Message: "ok",
	}

	switch req.GetThirdLoginType() {
	case publishThird_commion.LoginType_XSH:
		//小红书发布逻辑
		resp, err = application.PublishThirdApplicationSVC.GetXhsLoginQr(ctx)
		if err != nil {
			internalServerErrorResponse(ctx, c, err)
			return
		}
	}
	c.JSON(consts.StatusOK, resp)
}

// PublishToXHS .
// @router /api/publish_to_third/publish_to_xhs [POST]
func PublishToXHS(ctx context.Context, c *app.RequestContext) {
	var err error
	var req publishThird.GetXHSRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		invalidParamRequestResponse(c, err.Error())
		return
	}

	resp := &publishThird.PublishThirdResponse[string]{
		Code:    0,
		Message: "ok",
	}
	switch req.GetPublishType() {
	case publishThird_commion.PublishThirdType_XSH:
		//小红书发布逻辑
		resp, err = application.PublishThirdApplicationSVC.PublishNote(ctx, req)
		if err != nil {
			internalServerErrorResponse(ctx, c, err)
			return
		}

	}
	c.JSON(consts.StatusOK, resp)
}

// 刷新获取信息
func GetTweetInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req publishThird.GetTweetXHSRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		invalidParamRequestResponse(c, err.Error())
		return
	}

	resp := &publishThird.PublishThirdResponse[string]{}

	switch req.GetTweetInfoType() {
	case publishThird_commion.TweetType_XSH:
		resp, err = application.PublishThirdApplicationSVC.GetTweetInfo(ctx, req)
		if err != nil {
			internalServerErrorResponse(ctx, c, err)
			return
		}
	}

	c.JSON(consts.StatusOK, resp)
}
